#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

# Run the bootstrap script included with the dotfiles
if [ -f "${HOME}/.dotfiles/script/bootstrap" ]; then
	echo "Executing ${HOME}/.dotfiles/script/bootstrap"
	${HOME}/.dotfiles/script/bootstrap
fi

if [ "$system_type" = "Darwin" ]; then

  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

fi

# Make sure all our bin files are executable
chmod +x ~/bin/*
