#!/bin/sh
#
# dot_update
#
# `update` handles installation, updates, things like that. Run it
# periodically to make sure you're on the latest and greatest.
export DOTFILES="$HOME/.dotfiles"
cd "$HOME" || exit 1

# fixes PATH (we could be running from the crontab)
PATH="$(command -p getconf PATH):/usr/local/bin"

# load custom config if any
# shellcheck disable=SC1090
[ -f ~/.localrc ] && . ~/.localrc

# # ssh would not work under cron, add a https one
# if [[ ! $(git remote -v | grep -q updates) ]]; then
#     echo "› setting up update channel"
#     git remote add updates https://github.com/StephenBrown2/.files.git 2>/dev/null
# fi

# # Update repo
# echo "› git update"
# git pull --rebase --stat updates "$(git rev-parse --abbrev-ref HEAD)"

# # Update submodules
# echo "› submodules update"
# git submodule update --init --recursive --remote --merge --quiet

# Run all updates
find "${DOTFILES}" -name update.sh | while read updater; do
    echo "› ${updater}...";
    sh -c "${updater}";
done

# Run all installs
echo "› $DOTFILES/script/install"
"$DOTFILES/script/install"

if command -v antibody >/dev/null 2>&1; then
	echo "› antibody update"
	antibody update
fi

echo "› registering last update"
git config --global dotfiles.lastupdate "$(date +%Y%m%d%H%M)"