prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "docker_context",
    "package",
    "golang",
    "nim",
    "nodejs",
    "python",
    "ruby",
    "rust",
    "zig",
    "kubernetes",
    "memory_usage",
    # "aws",
    "env_var",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 25
style = "bold yellow"

[[battery.display]]  # "bold yellow" style when capacity is between 30% and 50%
threshold = 50
style = "bold fg:#FF7F00"

[directory]
fish_style_pwd_dir_length = 1

[docker_context]
disabled = false

[git_status]
show_sync_count = true
staged_count.enabled = true
stashed_count.enabled = true

[kubernetes]
disabled = false

[time]
disabled = false
format = " %T"
