# Essentially format = "$all", but we need to insert the custom.time module after the regular one
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
${custom.time}\
$status\
$shell\
$character"""

[aws]
disabled = true
format = "on [$symbol$profile(\\($region\\))]($style) "
style = "bold blue"
symbol = "🅰 "

[[battery.display]] # "bold red" style when capacity is between 0% and 15%
threshold = 15
style = "bold red"

[[battery.display]] # "bold orange" style when capacity is between 15% and 30%
threshold = 30
style = "bold fg:#FF7F00"

[[battery.display]] # "bold yellow" style when capacity is between 30% and 50%
threshold = 50
style = "bold yellow"

[directory]
fish_style_pwd_dir_length = 1

[docker_context]
disabled = false

[kubernetes]
disabled = false

[shlvl]
disabled = false

[terraform]
format = "via [💠 $version$workspace]($style) "

[time]
disabled = false
format = " [$time]($style) "
#format = "🕙 [$time]($style) "
time_range = "07:00:00-17:00:00"

[custom.time]
symbol = " "
command = "date '+%H:%M:%S'"
when = """[[ $(date "+%H") -gt 16 ]]"""
description = "Displayes the time after work"
style = "bold red"
disabled = false
